### PR TITLE
Backspace button update successful

### PR DESCRIPTION
**Pull request by SanskrutiRP**
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by sairish2001** [comment]
Have you made changes in index.html file?

**Comment by sairish2001** [comment]
id="backspace"

it seems you added id for the button only

**Review by sairish2001 — APPROVED** [review]
Well Done!
Thanks for your contribution

**Comment by SanskrutiRP** [comment]
Thank you!!!

**Pull request merged**
