### PR TITLE
Made website mobile and tablet friendly.

### PR DESCRIPTION
**Pull request by Aanchal116**
Hey @sairish2001 ,
Please check this PR. It would make the website mobile and tablet friendly by fixing issues with spacing and navbar.

### CODE REVIEW

**Review by sairish2001 — COMMENTED** [review]
Kindly remove the bootstrap cdn, I already linked the bootstrap file stored in the local folder

**Comment by Aanchal116** [comment]
> Kindly remove the bootstrap cdn, I already linked the bootstrap file stored in the local folder

Sure @sairish2001 , please let me know if there are any more changes required. Also , it would be great if you could please tell if I need to push the issue again? I'm new to this stuff.

**Comment by sairish2001** [comment]
Just make changes and commit them, it will reflect in this PR

**Comment by Aanchal116** [comment]
> Just make changes and commit them, it will reflect in this PR

Okay, thanks a lot.

**Comment by Aanchal116** [comment]
Hey @sairish2001 , I committed the changes , please acknowledge.

**Comment by sairish2001** [comment]
It's not visible, Click on PR for changes to reflect

**Review by sairish2001 — APPROVED** [review]

**Comment by sairish2001** [comment]
[#66](https://github.com/sairish2001/makesmatheasy.github.io/issues/66)

**Comment by Aanchal116** [comment]
Thankyou @sairish2001

**Pull request merged**
