### PR TITLE
svg-icons-added

### PR DESCRIPTION
**Pull request by Ankita297**
Makes Math Easy - Google Chrome 08-03-2021 17_47_38 (2)

### CODE REVIEW

**Comment by Ankita297** [comment]
Sir is it okay ?

**Comment by sairish2001** [comment]
don't leave empty `alt=" "` in img tag

**Comment by Ankita297** [comment]
okay . So should i make another PR.

**Comment by sairish2001** [comment]
no, you can make a commit into this PR also

**Pull request merged**
