### PR TITLE
Created Trigonometry values Table

### PR DESCRIPTION
**Pull request by janvi01**
Added a trigonometry table.
I am not familiar with Latex text, I will surely try to implement once I get it.

### CODE REVIEW

**Comment by sairish2001** [comment]
`Index.html` file is creating conflicts, as there are huge changes made by our contributor. I would suggest you to update your index.html file with a new one. and just copy/paste your <div id="trigonovaluestable">__whole code__</div>

**Comment by janvi01** [comment]
Do i have to make new index.html and paste only <div id="trigonovaluestable">__whole code__</div> this code or whole file code?

**Comment by sairish2001** [comment]
> Do i have to make new index.html and paste only
> 
> **whole code**
> this code or whole file code?

Great Work! Conflict resolved

**Comment by janvi01** [comment]
Thankyou sir, looking forward to contribute more.

**Pull request merged**
