### PR TITLE
Home button bug fixed

### PR DESCRIPTION
**Pull request by akshay399**

### CODE REVIEW

**Review by sairish2001 — COMMENTED** [review]
Have you checked it?
is it working fine!

after clicking home button it should close all the Calculators,

see appjs/working.js for the proper working of SideNav
and from appjs/index.js view the function openit() , which is responsible for Toggling the Calculators

**Comment by sairish2001** [comment]
Actually, your code is reloading the index.html file, we must not reloadit

**Comment by sairish2001** [comment]
you havev to close all the Calculators and toggle down the Home <div>

**Comment by akshay399** [comment]
> you havev to close all the Calculators and toggle down the Home <div>

Okk I am looking into it

**Comment by sairish2001** [comment]
There are some conflicts with your index.html file, I would suggest you to kindly update the code in your Repository to avoid conflicts

**Comment by akshay399** [comment]
> There are some conflicts with your index.html file, I would suggest you to kindly update the code in your Repository to avoid conflicts

i made necessary changes, please review it, thank you

**Review by sairish2001 — COMMENTED** [review]
Seems fine! just one thing left
[function openit()](https://github.com/sairish2001/makesmatheasy.github.io/blob/7984c20b556f466eca0842e377611e569c7e8ee0/appjs/index.js#L63)

Add id(`#home`) in `ids=[]` array in index.js -> function openit()

**Comment by akshay399** [comment]
> Seems fine! just one thing left
> [function openit()](https://github.com/sairish2001/makesmatheasy.github.io/blob/7984c20b556f466eca0842e377611e569c7e8ee0/appjs/index.js#L63)
> 
> Add id(`#home`) in `ids=[]` array in index.js -> function openit()

done, thank you :)

**Review by sairish2001 — APPROVED** [review]
Well Done

**Comment by sairish2001** [comment]
[#64](https://github.com/sairish2001/makesmatheasy.github.io/issues/64)

**Pull request merged**
