### PR TITLE
search bar animation

### PR DESCRIPTION
**Pull request by mridulabatra**
## Related Issuse

- Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Comment by mridulabatra** [comment]
good evening sir, please review the changes . if u r not happy with the changes, I can work on them. Thank you.

**Review by sairish2001 — APPROVED** [review]
Well Done!

**Comment by sairish2001** [comment]
[#44](https://github.com/sairish2001/makesmatheasy.github.io/issues/44)

**Comment by sairish2001** [comment]
There are some conflicts, in your PR, kindly update the code, make required changes

**Comment by mridulabatra** [comment]
Okh sir

**Pull request merged**
