### PR TITLE
Added the Documentation required by creating helpjavascript.html page #6

### PR DESCRIPTION
**Pull request by SHAIMA-HAQUE**
I have created the HTML page with the step by step method to enable JavaScript in their browsers

### CODE REVIEW

**Comment by sairish2001** [comment]
Great Work!
I want a few changes
- `<title>Makes Math Easy - Enable JavaScript</title>`
- Color Combination
    - Background (`#232a36`)
    - Pink (`#ff88e7`) for contrast
    - White for Text
 - Font Family
```
@font-face {
    font-family: mainfont;
    src: url(../fonts/Product_Sans_Regular.ttf) format('truetype');
}

@font-face {
    font-family: mainfontbold;
    src: url(../fonts/Product_Sans_Bold.ttf) format('truetype');
}
```
- use Font
    `font-family:mainfont;` or `font-family:mainfontbold;`

**Comment by SHAIMA-HAQUE** [comment]
Ok, will do.

**Comment by SHAIMA-HAQUE** [comment]
The icons are getting merged in the black background colour.

Should I change it to something like this or anything else that you may suggest

**Comment by sairish2001** [comment]
Apply to icons
`style=filter:invert(100%);`
it will invert the color from black to white

Instead to applying Pink- Black, Pink-Black blocks
use black color in body{}
`body{
    background-color: ___color code;
}`

Use only white colors, if suits use pink just for contrast.

**Comment by SHAIMA-HAQUE** [comment]
Ok so, black background with highlighted pink sections alternating ,right?

**Comment by sairish2001** [comment]
fine!
try to make borders round
`border-radius: 30px;`
it looks nice

**Comment by SHAIMA-HAQUE** [comment]
Is this looking good?

**Comment by sairish2001** [comment]
remove pink color, make it simple as others

and make a PR

**Comment by SHAIMA-HAQUE** [comment]
Ok .

**Comment by SHAIMA-HAQUE** [comment]
Made the PR

**Comment by sairish2001** [comment]
Appreciated your patience.
Well Done!

**Comment by SHAIMA-HAQUE** [comment]
Thank you so much! This was my first major contribution ,thank you so much for helping

**Pull request merged**
