### PR TITLE
search bar

### PR DESCRIPTION
**Pull request by mridulabatra**
## Related Issuse

- Info about Issue or bug

Closes: #[issue number that will be closed through this PR]

#### Describe the changes you've made

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |

### CODE REVIEW

**Review by sagar-barapatre — APPROVED** [review]

**Comment by shrey27tri01** [comment]
@mridulabatra Could you please add screenshots of the changes you made? The search bar is quite critical to the application, so we won't want to mess it up :smiley: 

Also, there are some merge conflicts arising. See if you can resolve them. If you face any difficulties, feel free to ask! :smiley:

**Comment by mridulabatra** [comment]
Okh sir

**Review by sairish2001 — APPROVED** [review]
Well Done!
Thanks for your contribution

**Comment by mridulabatra** [comment]
thank you sir

**Pull request merged**
