### PR TITLE
Added binery and decimal converter

### PR DESCRIPTION
**Pull request by amrzaki2000**
Closes: #128 

#### Describe the changes you've made
- Added Binary calculations list item in the sidebar in case their will be more future binary features.
- Added a Binary / Decimal converter that converts from and to binary and decimal numbers.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
|
image
 | <b>
image
 </b>
 <b>
image
</b> |

### CODE REVIEW

**Comment by amrzaki2000** [comment]
@sairish2001 
Kindly Review my PR.
Thank you 👍

**Review by sairish2001 — COMMENTED** [review]
PR is creating conflicts, kindly update your code in local machine and make required changes

**Comment by sairish2001** [comment]
Conflicts still there

**Comment by amrzaki2000** [comment]
> 
> 
> Conflicts still there

Check now, please

**Review by sairish2001 — APPROVED** [review]
Well Done!
Great Work 👍

**Comment by amrzaki2000** [comment]
> Well Done!
> Great Work 👍

Thanks ❤️🙏🏻

**Pull request merged**
