### PR TITLE
drop icon bug fixed #38

### LINKED ISSUE #38: dropDown menu image bug
The adjacent image in the DropDown menuList  (inside sideBar) shall show the correct collapsing direction.
Screenshot (16)_LI

### PR DESCRIPTION
**Pull request by Pranjal-Jayaswal**
The drop icon now changes accordingly with the collapsing direction of drop menu. #38

### CODE REVIEW

**Review by sairish2001 — APPROVED** [review]
Well Done!

**Comment by Pranjal-Jayaswal** [comment]
Well...Thanks for merging my PR in your main branch.(Learned a lot of new stuff from your project)

**Comment by Pranjal-Jayaswal** [comment]
> Well Done!

Well...Thanks for merging my PR in your main branch.(Learned a lot of new stuff from your project)

**Comment by sairish2001** [comment]
@Pranjal-Jayaswal Feeling glad, you learnt something 👍.

**Pull request merged**
