### PR TITLE
simple and compound interest

### PR DESCRIPTION
**Pull request by khareyash05**
Closes: #125 

#### Describe the changes you've made

Added a functionality of finding simple and compound interest when user enters principal amount,time and rate of interest

## Checklist:

- [ x ] My code follows the style guidelines of this project.
- [ x ] I have performed a self-review of my own code.
- [ x ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ x ] My changes generate no new warnings.

@sairish2001 Have a look!

### CODE REVIEW

**Review by sairish2001 — COMMENTED** [review]
PR is creating conflicts
Kindly Update your code in your local machine and make required changes, to avoid conflicts

**Comment by khareyash05** [comment]
@sairish2001 we have to type ```git pull origin main``` right?

**Comment by khareyash05** [comment]
We have to use ```git pull upstream master``` right?

**Comment by sairish2001** [comment]
our brach is main

**Comment by khareyash05** [comment]
Creating a new PR

**Pull request closed without merging**
