### PR TITLE
Backspace button update

### PR DESCRIPTION
**Pull request by SanskrutiRP**
I have made the changes as described.
## Checklist  :

- My code follows the style guidelines of this project.
- I have performed a self-review of my own code.
- I have commented my code, particularly in hard-to-understand areas.
- I have made corresponding changes to the documentation.
- My changes generate no new warnings.

### CODE REVIEW

**Review by sairish2001 — APPROVED** [review]
Well Done!
Great Work 👍

**Comment by sairish2001** [comment]
[#93](https://github.com/sairish2001/makesmatheasy.github.io/issues/93)

**Review by sairish2001 — COMMENTED** [review]
Your code is creating problem, Kindly update the code in your local repository and make required changes

**Comment by SanskrutiRP** [comment]
Thanks a lot for support 😊🙏

**Comment by SanskrutiRP** [comment]
> Your code is creating problem, Kindly update the code in your local repository and make required changes


I hope it is working!

**Comment by sairish2001** [comment]
> > Your code is creating problem, Kindly update the code in your local repository and make required changes
> 
> I hope it is working!

There's not a problem with your code, just update the code in your local machine and make required changes as some outdated code in your file is creating problem

**Comment by SanskrutiRP** [comment]
Okay wait

**Pull request merged**
