### PR TITLE
Issue 186- Light mode

### PR DESCRIPTION
**Pull request by Shubhrima**
## Related Issue

- Info about Issue or bug

Closes: #[issue number that will be closed through this PR]  186

#### Describe the changes you've made

Added a light mode to the project with a different color theme.

## Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] I have made corresponding changes to the documentation.
- [ x] My changes generate no new warnings.

## Screenshots

|        Original         |          Updated           |
| :---------------------: | :------------------------: |
| **original screenshot** | <b>updated screenshot </b> |
image
image

### CODE REVIEW

**Review by sairish2001 — COMMENTED** [review]
Can you please share some more screenshots

**Comment by Shubhrima** [comment]
image
image
image
image
image
image
image
image

**Comment by sairish2001** [comment]
The color of Heart button(favourite button) in dark mode changes

**Comment by sairish2001** [comment]
Also arithmetic buttons in calculator is white in color, they should be black

**Comment by Shubhrima** [comment]
image
image

**Review by sairish2001 — APPROVED** [review]
Well Done!
Thanks for your contribution

**Comment by Shubhrima** [comment]
> Well Done!
> Thanks for your contribution

This has been my first contribution. Thank you for helping me :)

**Pull request merged**
