### PR TITLE
Make Copyright Text Relative to Navbar

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #106 
Made Copyright Text Relative to Navbar

@sairish2001 Have a look!

### CODE REVIEW

**Comment by sairish2001** [comment]
reduce it's font Size, near about 10px

**Comment by khareyash05** [comment]
@sairish2001 Is this font size ok?

**Comment by sairish2001** [comment]
Reduce a little bit

**Comment by khareyash05** [comment]
@sairish2001  Reduced by 2 px

**Comment by khareyash05** [comment]
Reduced to 8px @sairish2001

**Comment by sairish2001** [comment]
Fine👍

**Comment by khareyash05** [comment]
Creating a commit

**Review by sairish2001 — APPROVED** [review]
Well Done!

**Comment by khareyash05** [comment]
Thank you!

**Pull request merged**
